name: "Build"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.6, 3.7, 3.8, 3.9]
    steps:
    - name: Repository Checkout
      uses: actions/checkout@v2
    - name: Python Setup
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Dependencies Installation
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt --use-feature=in-tree-build
        pip install flake8
        pip install sphinx
        pip install sphinx-autodoc-typehints
        pip install wheel
    - name: Linting
      run: |
        flake8 . --count --statistics --ignore=E501,F403,F405
    - name: Building Documents
      run: |
        make -C docs/ html
        touch docs/_build/html/.nojekyll
    - name: Building Package
      run: |
        python setup.py sdist bdist_wheel
