name: "Code Analysis"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '00 19 * * 5'

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    strategy:
      fail-fast: false
      matrix:
        language: [ 'python' ]
    steps:
    - name: Repository Checkout
      uses: actions/checkout@v2
    - name: Analysis Initialization
      uses: github/codeql-action/init@v1
      with:
        languages: ${{ matrix.language }}
    - name: Analysis Execution
      uses: github/codeql-action/analyze@v1
