name: Conda Test

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release Version:'
        required: true

jobs:
  release:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        language: [ python ]
    steps:
    - name: Repository Checkout
      uses: actions/checkout@v2
    - name: Python Setup
      uses: actions/setup-python@v2
      with:
        python-version: 3.x
        architecture: x64
    - name: Get SHA256
      id: sha256
      env:
        VERSION: ${{ github.event.inputs.version }}
      run: |
        sleep 1m
        wget https://pypi.io/packages/source/P/PyDTMC/PyDTMC-$VERSION.tar.gz -O /tmp/PyDTMC-$VERSION.tar.gz
        echo "::set-output name=SHA256::$(openssl sha256 /tmp/PyDTMC-$VERSION.tar.gz | awk '{print $2}')"
    - name: Set SHA256
      env:
        SHA256: ${{ steps.sha256.outputs.SHA256 }}
        SHA256_FILE: meta.yaml
        SHA256_REGEX: 'sha256: placeholder'
      run: |
        grep $SHA256_REGEX $SHA256_FILE
        sed -i "s/$SHA256_REGEX/sha256: /g" $VERSION_FILE
        grep $SHA256_REGEX $SHA256_FILE
    - name: Conda Installation
      run: |
        conda update conda
        conda install conda-build anaconda-client
        conda update conda-build anaconda-client
    - name: Build
      run: |
        conda config --set anaconda_upload no
        conda build . --output-folder /tmp/conda-build
  
