name: "Coverage"

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]



jobs:
  coverage:
    name: Coverage
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.6, 3.7, 3.8, 3.9]
    steps:
    - name: Repository Checkout
      uses: actions/checkout@v2
    - name: Python Setup
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Libraries Installation
      run: |
        sudo apt-get -q update
        sudo apt-get -y install graphviz
    - name: Dependencies Installation
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt --use-feature=in-tree-build
        pip install pydot
        pip install coverage
        pip install pytest-cov
    - name: Testing
      run: |
        pytest --cov=pydtmc tests/
    - name: Codecov Push
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        GITHUB_TOKEN: $CODECOV_TOKEN
      run: |
        pip install codecov
        codecov
    - name: Coveralls Push
      env:
        COVERALLS_SERVICE_NAME: github-actions
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
        GITHUB_TOKEN: $COVERALLS_REPO_TOKEN
      run: |
        pip install coveralls
        coveralls
