name: "Test"

on: [ workflow_dispatch ]

jobs:
  initialization:
    name: Initialization
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        python-version: [ 3.6, 3.7, 3.8, 3.9 ]
    steps:
    - name: Repository Checkout
      uses: actions/checkout@v2
    - name: Python Setup
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Python Cache
      id: cache
      uses: actions/cache@v2
      with:
        path: ${{ env.pythonLocation }}
        key: ${{ runner.os }}-${{ env.pythonLocation }}-${{ hashFiles('setup.cfg') }}
    - name: Dependencies Installation
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        pip install --upgrade pip
        pip install --upgrade --upgrade-strategy eager -r requirements.txt --use-feature=in-tree-build
        pip install --upgrade --upgrade-strategy eager -e .[lint]
        pip install --upgrade --upgrade-strategy eager -e .[docs]
        pip install --upgrade --upgrade-strategy eager -e .[setup]
        pip install --upgrade --upgrade-strategy eager -e .[package]
        pip install --upgrade --upgrade-strategy eager -e .[tests]
  documentation:
    name: Documentation
    needs: initialization
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        python-version: [ 3.6, 3.7, 3.8, 3.9 ]
    steps:
    - name: Repository Checkout
      uses: actions/checkout@v2
    - name: Python Setup
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Python Cache
      id: cache
      uses: actions/cache@v2
      with:
        path: ${{ env.pythonLocation }}
        key: ${{ runner.os }}-${{ env.pythonLocation }}-${{ hashFiles('setup.cfg') }}
    - name: Dependencies Installation
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        pip install --upgrade pip
        pip install --upgrade --upgrade-strategy eager -r requirements.txt --use-feature=in-tree-build
        pip install --upgrade --upgrade-strategy eager -e .[docs]
    - name: Documentation
      run: make -C docs/ html
